In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 

In [3]:
df=pd.read_csv("C:\\Users\\parth\\OneDrive\\Desktop\\parth\\Machine-learning\\Machine-learning\\08-Linear-Regression-Models\\Advertising.csv")

In [4]:
X=df.drop('sales',axis=1)

In [5]:
y=df['sales']

In [6]:
from sklearn.preprocessing import PolynomialFeatures

In [7]:
polynomial_converter=PolynomialFeatures(degree=3,include_bias=False)

In [8]:
poly_features=polynomial_converter.fit_transform(X)

In [9]:
poly_features.shape

(200, 19)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scalar=StandardScaler()

In [14]:
scalar.fit(X)

StandardScaler()

In [15]:
X_train=scalar.fit_transform(X_train)

In [16]:
X_test=scalar.fit_transform(X_test)

In [17]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

Ridge Regression 

In [18]:
from sklearn.linear_model import Ridge

In [19]:
ridge=Ridge(alpha=10)

In [20]:
ridge.fit(X_train,y_train)

Ridge(alpha=10)

In [21]:
test_prediction=ridge.predict(X_test)

In [22]:
test_prediction

array([14.72040305, 19.68162602, 12.77344563, 17.13398747,  9.94195003,
        9.09273492, 20.53255998, 17.5642862 , 11.20240863, 20.23898279,
       11.31581283, 14.23554699, 12.98024107, 23.70241564, 19.68719787,
       10.75211826, 13.43050956, 10.11553321,  9.83940033, 21.87053342,
        9.29351427, 19.44860351, 28.37065001, 25.16018616, 10.10302856,
       12.52511663, 21.26203177, 10.34552979, 13.07082093, 10.2295026 ,
       10.36119434, 20.31219195, 11.46768434,  8.94165105, 18.31818676,
       10.29147399, 11.12043731, 10.44374713,  9.71463738, 11.64518818,
       12.90784926, 11.28592455, 11.85706836,  9.4709617 , 12.30076777,
       11.32095318,  9.05923001, 15.76329188, 13.65980715, 22.98481942,
       11.8378082 , 13.71101394, 15.28617314, 12.27189133, 12.46062141,
        8.26891502, 25.80885832, 11.40749321, 17.96986163, 15.81533423])

In [23]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [24]:
MAE=mean_absolute_error(y_test,test_prediction)

In [25]:
MSE=mean_squared_error(y_test,test_prediction)

In [26]:
RSME=np.sqrt(MSE)

In [27]:
MAE

0.9670410375853886

In [28]:
RSME

1.3327611545386266

In [29]:
from sklearn.linear_model import RidgeCV

In [30]:
ridge_cv_model=RidgeCV(alphas=(0.1,1.0,10.0),scoring='neg_mean_absolute_error') # higher the negative mean absolute better it is because it is negative 

In [31]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(scoring='neg_mean_absolute_error')

In [32]:
ridge_cv_model.alpha_ # this tell which alpha parameter performance best 

0.1

In [33]:
#from sklearn.metrics import SCORERS

In [34]:
test_prediction=ridge_cv_model.predict(X_test)

In [35]:
MAE=mean_absolute_error(y_test,test_prediction)

In [36]:
MSE=mean_squared_error(y_test,test_prediction)

In [37]:
RSME=np.sqrt(MSE)

In [38]:
MAE

0.9873965312429

In [39]:
RSME

1.167668988604158

In [40]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

# LASSO 
Least absolute shrinkage and selection operator

In [41]:
from sklearn.linear_model import LassoCV

In [42]:
lassocv_model=LassoCV(eps=0.001,n_alphas=100,cv=10,max_iter=10000000) # eps=min_aplha/max_alpha N_alhas=Number of times alpha u want cv number of folds in cross validation 

In [43]:
lassocv_model.fit(X_train,y_train)

LassoCV(cv=10, max_iter=10000000)

In [44]:
lassocv_model.alpha_

0.004943070909225827

In [45]:
test_prediction=lassocv_model.predict(X_test)

In [46]:
MAE=mean_absolute_error(y_test,test_prediction)

In [47]:
MSE=mean_squared_error(y_test,test_prediction)
RSME=np.sqrt(MSE)

In [48]:
MAE

0.9723939145391844

In [49]:
RSME

1.1570105786801914

In [50]:
lassocv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [51]:
from sklearn.linear_model import ElasticNetCV

In [53]:
elastic_model=ElasticNetCV(l1_ratio=[.1,.5,.7,.9,.95,.99,1],
                           eps=0.001,
                           n_alphas=100,
                           max_iter=1000000)

In [54]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [55]:
elastic_model.l1_ratio_ # underscore gives the best parameter

1.0

In [56]:
elastic_model.alpha_

0.004943070909225827

In [57]:
lassocv_model.alpha_

0.004943070909225827

In [59]:
test_predictions=elastic_model.predict(X_test)

In [60]:
MAE=mean_absolute_error(y_test,test_prediction)

In [61]:
RSME=np.sqrt(mean_squared_error(y_test,test_prediction))

In [62]:
MAE

0.9723939145391844

In [63]:
RSME

1.1570105786801914