In [12]:
text=['This is  a line',
      'This is another line',
      'Completely Different line']

In [26]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

In [14]:
help(CountVectorizer)

Help on class CountVectorizer in module sklearn.feature_extraction.text:

class CountVectorizer(_VectorizerMixin, sklearn.base.BaseEstimator)
 |  CountVectorizer(*, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern='(?u)\\b\\w\\w+\\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.int64'>)
 |
 |  Convert a collection of text documents to a matrix of token counts.
 |
 |  This implementation produces a sparse representation of the counts using
 |  scipy.sparse.csr_matrix.
 |
 |  If you do not provide an a-priori dictionary and you do not use an analyzer
 |  that does some kind of feature selection then the number of features will
 |  be equal to the vocabulary size found by analyzing the data.
 |
 |  For an efficiency comparison of the different feature extractors, see
 |  :ref:`sphx_glr_auto_examp

In [24]:
cv=CountVectorizer(stop_words='english')  #remove the common word like the a u can also pass custom stop word i.e common word...etc 

In [20]:
sparse_matrix=cv.fit_transform(text)

In [ ]:
sparse_matrix.todense()
1

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]], dtype=int64)

In [23]:
cv.vocabulary_  # unique word

{'line': 2, 'completely': 0, 'different': 1}

In [28]:
tfdf=TfidfTransformer()

In [29]:
sparse_matrix

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [30]:
results=tfdf.fit_transform(sparse_matrix)

In [31]:
results.todense()

matrix([[0.        , 0.        , 1.        ],
        [0.        , 0.        , 1.        ],
        [0.65249088, 0.65249088, 0.38537163]])

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer # does both Count Vectorizer and Transform _inverse Document

In [33]:
tv=TfidfVectorizer()

In [34]:
tv_result=tv.fit_transform(text)

In [35]:
tv_result

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [36]:
tv_result.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])