In [4]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import plotly as px

In [5]:
import plotly.graph_objects as go

# line plot

In [6]:
years=np.arange(2010,2021)
sales=np.array([100,120,150,170,200,220,250,300,350,400,450])

In [7]:
years

array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020])

In [15]:
fig = go.Figure(data=go.Scatter(x=years, y=sales, name='Sales Data'))
fig.update_layout(
    title='Year VS Sales',
    xaxis_title='Years',
    yaxis_title='Sales',
    showlegend=False
)
fig.show(renderer='browser') 

# scatterplot

In [18]:
age=np.arange(20,60,5)
scores=np.array([50,90,60,80,70,90,100,110])

In [19]:
age

array([20, 25, 30, 35, 40, 45, 50, 55])

In [20]:
scores

array([ 50,  90,  60,  80,  70,  90, 100, 110])

In [21]:
fig=go.Figure(data=go.Scatter(x=age,y=scores,mode='markers'))
fig.show(renderer='browser')

Modifications

In [26]:
fig=go.Figure(data=go.Scatter(x=age,y=scores,mode='markers',marker=dict(
    color='blue',
    size=10,
    symbol='triangle-up',
    line=dict(
        color='red',
        width=2
    )
)))
fig.show(renderer='browser')

# Error Bars

In [32]:
fig=go.Figure(data=go.Scatter(x=age, y=scores, mode='markers', marker=dict(
    color='blue'
)))
fig.update_traces(error_y=dict(
        type='data',
        array=[3,2,4,1,2,3,2,3],
        visible=True
    )
)
fig.show(renderer='browser')

Bubble charts used when the data is categorical ,to represent the relationship between 
variables

In [33]:
cities=['Mumbai','Delhi','Banglore','Kolkata']
population=[20,15,10,8]
temperature=[30,35,32,28]
gdp=[100000,200000,150000]

In [34]:
fig=go.Figure(data=go.Scatter(x=temperature,y=population,mode='markers',
    marker=dict(
        size=gdp,
        sizemode="area",
        sizeref=max(gdp)/10000,
        sizemin=2,
        color='red',
        showscale=True
    )
    ,text=cities))

fig.show(renderer='browser')
