NUMPY

In [ ]:
import numpy as np


In [3]:
mylist=[1,2,3]
np.array(mylist)

array([1, 2, 3])

In [4]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
mymatrix=np.array(matrix)

In [5]:
print(mymatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
np.arange(0,10) # create the array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)# first par= start,second=stop not included ,third par=step size means jumping it from it

array([0, 2, 4, 6, 8])

In [10]:
np.zeros((2,5)) # RC row ,columns 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.one((4,4))

AttributeError: module 'numpy' has no attribute 'one'

In [12]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,10,3) # 3 point between 0 and 10 and always use even spacing because it is human-readable

array([ 0.,  5., 10.])

In [19]:
np.linspace(0,5,11) # 11 points present hai

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [21]:
np.eye(3) # to create  identity  matrix pass dimension in it for ex like 3 for 3x3 matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Numpy random function

In [22]:
np.random.rand(3,3) # create an array of random number that falls in between 0-1

array([[0.41472832, 0.64977368, 0.94258704],
       [0.35851752, 0.03980522, 0.8524547 ],
       [0.90106156, 0.42020167, 0.26589063]])

Normal distribution
means jo bhi common or in general like height of person 5 is commmon in india so that will be appear most in the graph
in this case the numbers near to the zero will appear most in the graph

In [24]:
np.random.randn(3,3) 

array([[ 0.7970738 ,  0.4711162 , -2.38692419],
       [ 0.97769093,  0.31508785,  0.8698657 ],
       [-0.58590036,  2.66439846,  0.36538323]])

In [26]:
np.random.randint(0,101,(3,3)) # provide the starting point also ending point also size of it 3x3 matrix

array([[25, 94, 21],
       [47, 91, 77],
       [33, 70, 68]])

In [30]:
np.random.seed(42) #seed means the same random will be generated if u use it again and again 
np.random.rand(4)   # even if you redo it will generated same random number 
# if don't use the seed then different random number will be generated each time you run the code 


array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [33]:
arr=np.arange(0,25)
arr.repeat(5,5)
arr.reshape(5,5)

AxisError: axis 5 is out of bounds for array of dimension 1

In [37]:
arr=np.arange(0,25)
print(arr)
arr.reshape(5,5) # reshape size must equal to the 25 or end point

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
ranarr=np.random.randint(0,101,10)
print(ranarr)
ranarr.max()
ranarr.min()
ranarr.argmax() # return the index of the max value
ranarr.dtype

[ 8 89 52  1 83 91 59 70 43  7]


dtype('int32')

In [46]:
arr.shape

(25,)