In [3]:
import numpy as np

arr=np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr+5


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [9]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
arr/arr

C:\Users\parth\AppData\Local\Temp\ipykernel_9292\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/arr # in python it will give errors but in numpy it will just give the warning and return the result for ex-inf

C:\Users\parth\AppData\Local\Temp\ipykernel_9292\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [14]:
np.sqrt(arr) # takes the square root 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [16]:
np.sin(arr) # take angles as array

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [18]:
np.log(arr) # take logs of each element in the array

C:\Users\parth\AppData\Local\Temp\ipykernel_9292\2155513200.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # take logs of each element in the array


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [20]:
arr.sum() # take sum of all element present in the array 

55

In [22]:
arr.mean() # takes mean of all element in the array

5.0

In [24]:
arr.var() #  variance

10.0

In [26]:
arr.std() # standard deviation

3.1622776601683795

In [32]:
arr2d=np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr2d.sum()

300

In [36]:
arr2d.sum(axis=0)  # columns

array([50, 55, 60, 65, 70])

In [37]:
arr2d.sum(axis=1) # rows

array([ 10,  35,  60,  85, 110])