In [4]:
import numpy as np


In [5]:
arr=np.arange(0,11)

In [6]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
my_slice_arr=arr[:5]

In [8]:
my_slice_arr[:]=100
print(my_slice_arr)

[100 100 100 100 100]


In [9]:
print(arr)
arr[0:5]=100
arr=np.arange(0,11)
my_slice_arr=arr[0:5]
print(my_slice_arr)

[100 100 100 100 100   5   6   7   8   9  10]
[0 1 2 3 4]


In [10]:
my_slice_arr[:]=99 # assign all 99 to the array means jitna size hai utne 99 bharo 
my_slice_arr

array([99, 99, 99, 99, 99])

In [11]:
#it will be also affect the original array
arr
# if you don't want to affect the original array set the copy of it
arr_copy=arr.copy()
arr_copy[:]=99
print(f"This is the copy of array:{arr_copy}")
print(f"the Original array is{arr}")

This is the copy of array:[99 99 99 99 99 99 99 99 99 99 99]
the Original array is[99 99 99 99 99  5  6  7  8  9 10]


2D -array indexing 


In [12]:
array_2d=np.array([[2,4,6],[8,10,12],[14,16,18]])
array_2d[0] # single row
array_2d[0][0]# single element

2

In [13]:
array_2d.shape # returns the size 
array_2d[:2] # returns the two 
array_2d[:1,1:]  #left side row and right side columns

array([[4, 6]])

Conditional array

In [36]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
bool_arr=arr>4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [40]:
arr[bool_arr] # returns or show only those element which satisfies only true condition

array([ 5,  6,  7,  8,  9, 10])

In [41]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])